# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89165d43e4d2208564217f1b0b80b2f0e63c3453cb271fd7a2ca482bb9621843f6b649ac1e394b7483f7bc8920a1d7f5fff9f2591ac87b9a9b51fc26b5e44b93

test:
  secret_key_base: 7d2059219942aaecd38ccb1b3c4925c45593c086f00c480fa3bb824f27608b20b1d2a80df7c7c2c5ce5cda3d2374e295eebb6c47b3d41366c95cf095cfc5661e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
